# Generated by Django 4.1.6 on 2023-06-23 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohit', '0002_alter_projects_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='projects',
            name='video_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
