# Generated by Django 4.1.6 on 2023-06-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mohit', '0003_projects_image_projects_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_projects',
            name='Featured_project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mohit.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
