# Generated by Django 4.1.6 on 2023-06-24 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohit', '0004_alter_featured_projects_featured_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=10000)),
                ('link', models.CharField(blank=True, max_length=1000, null=True)),
                ('research_type', models.CharField(choices=[('P', 'Patent'), ('B', 'Featured in book'), ('RP', 'Research paper'), ('RV', 'Review paper')], max_length=100)),
                ('publication', models.CharField(max_length=100)),
            ],
        ),
    ]
