# Generated by Django 4.1.6 on 2023-06-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohit', '0005_research'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='tagline',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
