# Generated by Django 4.1.6 on 2023-06-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohit', '0006_projects_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='summary',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
