# Generated by Django 4.1.6 on 2023-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mohit', '0007_alter_research_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='featured_projects',
            name='tagline',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
