# Generated by Django 4.1.6 on 2023-05-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=10000)),
                ('images1', models.ImageField(upload_to='')),
                ('images2', models.ImageField(upload_to='')),
                ('images3', models.ImageField(upload_to='')),
                ('imp_Links', models.CharField(max_length=250)),
                ('references', models.CharField(max_length=400)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_effect.category')),
            ],
        ),
    ]
