# Generated by Django 4.1.6 on 2023-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_effect', '0003_alter_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='shares',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
